from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
EXPR_DIR = SCRIPT_DIR / "DATA" / "expr"

CAN_COLUMN = "Strain@B3_2.RN_1"


def load_data(path: Path) -> pd.DataFrame:
    """Read the CSV using consistent typing for large Adams exports."""
    return pd.read_csv(path, low_memory=False)


def filter_data(
    df: pd.DataFrame,
    time_col: str,
    start_time: float,
    end_time: float,
) -> pd.DataFrame:
    """Return rows whose time column lies inside the [start, end] window."""
    time_series = pd.to_numeric(df[time_col], errors="coerce")
    mask = (time_series >= start_time) & (time_series <= end_time)
    filtered = df.loc[mask].copy()
    filtered[time_col] = time_series[mask]
    return filtered


def smooth_series(series: pd.Series, window: int) -> pd.Series:
    """Run a rolling mean to dampen noise."""
    return series.rolling(window=window, min_periods=1).mean()


def create_axes():
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.set_facecolor("white")
    return fig, ax


def plot_can_pressure(ax, df: pd.DataFrame, start_time: float):
    textstyle = {"family": "Times New Roman", "size": 32}
    tick_font = "Times New Roman"
    tick_fontsize = 20
    ax.plot(
        df["t"] - start_time,
        smooth_series(pd.to_numeric(df[CAN_COLUMN], errors="coerce"), window=5),
        color="navy",
        linestyle="-",
        label="can@press.RN_1",
    )
    ax.set_xlabel("Time (s)", fontdict=textstyle)
    ax.set_ylabel("Contact Force (N)", fontdict=textstyle)
    ax.legend(fontsize=20)
    plt.xticks(fontsize=tick_fontsize, fontfamily=tick_font)
    plt.yticks(fontsize=tick_fontsize, fontfamily=tick_font)
    plt.tight_layout()
    return ax


def main():
    path = EXPR_DIR / "MR_door (run 24)_out.csv"
    df = load_data(path)
    start_time = 60.9
    end_time = 63
    filtered = filter_data(df, "t", start_time, end_time)

    fig, ax = create_axes()
    ax = plot_can_pressure(ax, filtered, start_time)

    output_folder = SCRIPT_DIR / "validation_outputs"
    output_folder.mkdir(parents=True, exist_ok=True)
    output_path = output_folder / "expr_force.png"
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    print(f"Plot saved to {output_path.resolve()} (generated by {Path(__file__).name})")


if __name__ == "__main__":
    main()
