from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
EXPR_DIR = SCRIPT_DIR / "DATA" / "expr"
SIM_DIR = SCRIPT_DIR / "DATA" / "sim"

CAN_COLUMN = "can@press.RN_6"
SIM_TIME_COL = "TIME"
SIM_PRESS_COL = "U2"


def load_data(path: Path) -> pd.DataFrame:
    """Read the CSV using consistent typing for large Adams exports."""
    return pd.read_csv(path, low_memory=False)


def filter_data(
    df: pd.DataFrame,
    time_col: str,
    start_time: float,
    end_time: float,
) -> pd.DataFrame:
    """Return rows whose time column lies inside the [start, end] window."""
    time_series = pd.to_numeric(df[time_col], errors="coerce")
    mask = (time_series >= start_time) & (time_series <= end_time)
    filtered = df.loc[mask].copy()
    filtered[time_col] = time_series[mask]
    return filtered


def smooth_series(series: pd.Series, window: int) -> pd.Series:
    """Run a rolling mean to dampen noise."""
    return series.rolling(window=window, min_periods=1).mean()


def create_axes():
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.set_facecolor("white")
    return fig, ax


def plot_can_pressure(ax, df: pd.DataFrame, start_time: float):
    """Plot the experiment strain gauge pressure and align time to 0 at the window start."""
    textstyle = {"family": "Times New Roman", "size": 32}
    tick_font = "Times New Roman"
    tick_fontsize = 20
    ax.plot(
        df["t"] - start_time,
        smooth_series(pd.to_numeric(df[CAN_COLUMN], errors="coerce"), window=5),
        color="navy",
        linestyle="-",
        label="Experiment: can@press.RN_1",
    )
    ax.set_xlabel("Time (s)", fontdict=textstyle)
    ax.set_ylabel("Contact Force (N)", fontdict=textstyle)
    plt.xticks(fontsize=tick_fontsize, fontfamily=tick_font)
    plt.yticks(fontsize=tick_fontsize, fontfamily=tick_font)
    plt.tight_layout()
    return ax


def plot_sim_pressure(ax, df: pd.DataFrame):
    """Plot the simulation result exported from Adams (DATA/sim)."""
    textstyle = {"family": "Times New Roman", "size": 32}
    tick_font = "Times New Roman"
    tick_fontsize = 20
    ax.plot(
        df[SIM_TIME_COL],
        smooth_series(pd.to_numeric(df[SIM_PRESS_COL], errors="coerce"), window=3),
        color="darkorange",
        linestyle="--",
        label=f"Sim: req_PRESS.{SIM_PRESS_COL}",
    )
    ax.set_xlabel("Time (s)", fontdict=textstyle)
    ax.set_ylabel("Contact Force (N)", fontdict=textstyle)
    plt.xticks(fontsize=tick_fontsize, fontfamily=tick_font)
    plt.yticks(fontsize=tick_fontsize, fontfamily=tick_font)
    plt.tight_layout()
    return ax


def main():
    expr_path = EXPR_DIR / "MR_door (run 29)_out.csv"
    sim_path = SIM_DIR / "req_PRESS_clean.csv"
    expr_df = load_data(expr_path)
    sim_df = load_data(sim_path)
    start_time = 54.35
    end_time = 54.35+1.3
    sim_end_time = 1.3
    filtered_expr = filter_data(expr_df, "t", start_time, end_time)
    filtered_sim = filter_data(sim_df, SIM_TIME_COL, 0, sim_end_time)

    fig, ax = create_axes()
    ax = plot_can_pressure(ax, filtered_expr, start_time)
    ax = plot_sim_pressure(ax, filtered_sim)
    ax.legend(fontsize=20, loc="upper left")

    output_folder = SCRIPT_DIR / "validation_outputs"
    output_folder.mkdir(parents=True, exist_ok=True)
    output_path = output_folder / "expr_can_press_294.png"
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    print(f"Plot saved to {output_path.resolve()} (generated by {Path(__file__).name})")


if __name__ == "__main__":
    main()
